### ISSUE TITLE
segfaults at "Show"

### ISSUE THREAD

**Issue by jjvz** [spaulaus/RootHistogramViewer#2]
Code compiles, and initializes, but when histogram is selected and "Show" is pressed,  *** Break *** segmentation violation error occurs. Check MainFrame.cpp, [line 126](https://github.com/spaulaus/RootHistogramGUI/blob/6c963bed2c17409ee7c3896e30fc624dab744cce/MainFrame.cpp#L126)... (some Freudian slip??)

I compiled and built it with cmake as per instructions, also with my rootcint and g++ process, all give same results. Code initializes, but crashes at "Show" button.

**Comment by jjvz** [comment]
Changed line 126  in MainFrame.cpp to:
TH1D *hist1d = (TH1D*)temp1d->Clone(); 

However, this makes the plotting VERY sluggish! And no updating of live histogram data either.

**Comment by spaulaus** [comment]
Just delete "clone" I'm not sure how that was committed to the repository.
